name: Java CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Extract configuration
        run: |
          echo -n "SECRING" | gpg --import > ./gpg.logs
          echo -n "SETTINGS" > ./settings.xml
        env:
          SECRING: ${{secrets.SECRING}}
          SETTINGS: ${{secrets.SETTINGS}}
      - name: Build with Maven
        run: mvn verify --settings ./settings.xml --batch-mode --update-snapshots -DskipTests=true -B
