name: Java CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Extract configuration
        run: |
          echo -n "$MAVEN_SITE" > ./settings.xml
#          echo -n "$SECRING" | gpg --import 2> ./gpg.logs
#          echo -n "$SETTINGS" > ./settings.xml
        env:
          MAVEN_SITE: ${{secrets.MAVEN_SITE}}
#          SECRING: ${{secrets.SECRING}}
#          SETTINGS: ${{secrets.SETTINGS}}
#      - name: Build with Maven
#        run: mvn verify --settings ./settings.xml --batch-mode --update-snapshots -DskipTests=true -B
      - name: Build with Maven
        run: mvn verify site site:stage scm-publish:publish-scm --batch-mode --update-snapshots -DskipTests=true -B
