name: Java CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Extract Public Key Ring
        run: echo ${{secrets.pubring}} | base64 --decode > ./pubring.gpg
      - name: Extract Secret Key Ring
        run: echo ${{secrets.secring}} | base64 --decode > ./secring.gpg
      - name: Extract Maven settings
        run: echo ${{secrets.settings}} | base64 --decode > ./settings.xml
      - name: Build with Maven
        run: mvn verify --settings ./settings.xml --batch-mode --update-snapshots -DskipTests=true -B
